hide_download: true
hide_download_original: null
leftnav:
- identifier: 71d22b2b-1f68-9cd9-1458-56b4b3ccef2a
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 2d071460-1ec8-d6cc-4b12-40428e3b4c92
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 6cd9e7f4-db90-cd08-47f5-e462469c19af
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 92e6f619-9440-f9fd-de1f-2affb51ec269
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 6fe3ecb8-0a9a-ac1b-8c93-10759403bbe9
  name: Tools
  pageRef: /pages/tools
  weight: 50
- identifier: 16c26e40-a092-2015-181e-34a102b27256
  name: Conference Videos
  pageRef: /pages/conference-videos
  weight: 60
